name = "osrs-flip-worker2"
main = "worker.js"
compatibility_date = "2025-08-01"

# When deploying this worker, specify routes in Cloudflare dashboard or here.
# Uncomment and edit the following lines if you want to bind to a domain:
# [routes]
# [outes]
routes = [ { pattern = "osrsfliptips.com/*", zone_name = "osrsfliptips.com" }, { pattern = "www.osrsfliptips.com/*", zone_name = "osrsfliptips.com" } ]
